apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: kafka-config
  labels:
    app: kafka
data:
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: "1"
  KAFKA_BROKER_ID: "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-0.kafka-headless:9093"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-0.kafka-headless:9092,EXTERNAL://localhost:9094"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_LOG_RETENTION_MS: "86400000"
  KAFKA_LOG_SEGMENT_BYTES: "1073741824"
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
