apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: mongodb-users-secret
type: Opaque
stringData:
  mongodb-root-username: admin
  mongodb-root-password: uitgo123
  mongodb-database: uitgo_users