apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: default
  name: trip-service-route
  labels:
    app: trip-service
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`trip.localhost`) || PathPrefix(`/api/trips`) || PathPrefix(`/socket.io`)
      kind: Rule
      services:
        - name: trip-service
          port: 3000
      middlewares:
        - name: trip-api-middleware
          namespace: default
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: trip-api-middleware
  labels:
    app: trip-service
spec:
  chain:
    middlewares:
      - name: trip-api-cors
      - name: compression
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: trip-api-cors
  labels:
    app: trip-service
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
      - "Accept"
      - "Origin"
    accessControlAllowCredentials: true
    accessControlMaxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compression
  labels:
    app: trip-service
spec:
  compress: {}
